### ISSUE TITLE
Trello graphical update disabled extension

### ISSUE THREAD

**Issue by anicolod78** [fredericseiler/trelabels#21]
With the recent changes in trello, some graphical element moved in different places and the extension stopped to work.

**Comment by fredericseiler** [comment]
Hi, thanks for the heads up.

I quickly looked at the new UI, and the integration of the Trelabels button will be more difficult than it was.

I'm convinced that making a Trello power-up will be way more efficient than constantly updating the extension when the UI changes, but I definitely don't have bandwidth for that. Also, I wonder if it's worth the hassle since Trello implemented a way to show label names on cards by clicking on labels...

Anyway, I'll see what I can do, but don't expect too much 😬
